### ISSUE TITLE
Tool window sometimes becomes empty when having multiple project windows

### ISSUE THREAD

**Issue by nogurenn** [halirutan/IntelliJ-Key-Promoter-X#17] opened 2018-03-19 04:04 UTC
OS: Mac OS X (10.12.6)
IDE: IntelliJ IDEA 2017.3.4 (Ultimate Edition)

I was routinely cycling between related projects via `CMD + backquote` when I noticed the key promoter tool window becomes empty at some point. RAM isn't a concern as system diagnostics indicate I have more than enough. Toggling the promoter window in between switching project windows is the most specific I can get, I apologize. It may be worth noting that having the promoter window open in more than one project seems to be causing the odd behavior.

**Comment by halirutan** [comment] 2018-04-25 14:29
Hmm, seems odd. I will investigate when I have some more time as I currently cannot think why this should happen. Thanks for the report.

**Comment by halirutan** [comment] 2018-07-05 14:39
OK, I could reproduce this now. It seems that this can be triggered when you have 2 windows open. In the first one, the KPX is tool-window is already open and then you open the tool-window in the second window.

It looks like the KPX panel of the first IDEA is disposed at this moment. Let's see what I did wrong. Thanks for the report again.

**Comment by halirutan** [comment] 2018-07-06 14:40
Fixed in dev-version and soon to be published. My model-view-controller implementation was a mess. I must have been drunk. I simplified it and now this should work.

**Closed by halirutan** 2018-07-06 14:40 UTC
Labels: bug
