### ISSUE TITLE
"Command Go to Declaration and Usages missed" reported when closing a tab with middle mouse click

### ISSUE THREAD

**Issue by arphox** [halirutan/IntelliJ-Key-Promoter-X#89] opened 2022-02-08 10:07 UTC
**Describe the bug**
"Command Go to Declaration and Usages missed" is reported when closing a tab with middle mouse click. Middle mouse click is also bound for the listed action, but should not be reported when I just simply close the tab.

**To Reproduce**
It is in the description, but see this video too:
![2022-02-08_11-01-04 654_rider64](https://user-images.githubusercontent.com/17320094/152965161-8dbdaa45-7f18-4a6f-a5d9-04785064e7c1.gif)

**Expected behaviour**
Do not show this recommendation as it is not a usage of the _Go to Declaration and Usages_ command.

**Screenshots**
See the video.

**Please also provide:**
 - OS: Windows 10 21H2
 - IntelliJ Product: JetBrains Rider 2021.3.3
 - Wolfram Plugin Version: I don't know what is this.

**Comment by halirutan** [comment] 2022-02-08 10:12
Duplicate of 

- #59

I explain in the comments that this is specific to Rider on Windows and there's nothing much I can do about it.

**Closed by halirutan** 2022-02-08 10:12 UTC
