### ISSUE TITLE
Not compatible with Android Studio Koala | 2024.1.1 Canary 3

### ISSUE THREAD

**Issue by ydonev** [halirutan/IntelliJ-Key-Promoter-X#122] opened 2024-04-06 21:11 UTC
**Describe the bug**
Plug in is not working with Android Studio Koala

**To Reproduce**
Steps to reproduce the behaviour:
1. Install latest Android Studio from Canary channel
2. Try to install the plugin
 
**Expected behaviour**
The plug in to be installed and working as expected

**Actual behaviour**
Plug in is not compatible with latest AS and IDE 233.* and cannot be installed

**Comment by halirutan** [comment] 2024-04-07 02:03
See here https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/118#issuecomment-2041274963

**Comment by halirutan** [comment] 2024-04-10 00:55
Duplicate of #118

**Closed by halirutan** 2024-04-10 00:55 UTC
