### ISSUE TITLE
Support for IntelliJ Idea 2024 version

### ISSUE THREAD

**Issue by ved-asole** [halirutan/IntelliJ-Key-Promoter-X#119] opened 2024-04-05 08:32 UTC
**Is your feature request related to a problem? Please describe.**
Support for IntelliJ Idea 2024 version

**Describe the solution you'd like**
Support for IntelliJ Idea 2024 version

**Describe alternatives you've considered**
Support for IntelliJ Idea 2024 version

**Additional context**
![image](https://github.com/halirutan/IntelliJ-Key-Promoter-X/assets/77259804/0481ffd3-0124-467e-b765-6b67a032c413)

**Comment by sprankhub** [comment] 2024-04-05 11:49
Duplicate of #118.

**Closed** 2024-04-06 18:23 UTC
Labels: feature-request
