### ISSUE TITLE
Support for PHPStorm version 2024.1

### ISSUE THREAD

**Issue by rubenromao** [halirutan/IntelliJ-Key-Promoter-X#121] opened 2024-04-06 12:36 UTC
Can you please add support for version 2024.1 PHPStorm?

**Comment by halirutan** [comment] 2024-04-07 02:03
See here https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/118#issuecomment-2041274963

**Comment by halirutan** [comment] 2024-04-10 00:55
Duplicate of #118

**Closed by halirutan** 2024-04-10 00:55 UTC
Labels: feature-request
