### ISSUE TITLE
support for pycharm 2024.1

### ISSUE THREAD

**Issue by HjtDevs** [halirutan/IntelliJ-Key-Promoter-X#120] opened 2024-04-06 11:44 UTC
support for pycharm 2024.1
support for pycharm 2024.1
support for pycharm 2024.1
support for pycharm 2024.1
support for pycharm 2024.1
support for pycharm 2024.1

**Comment by halirutan** [comment] 2024-04-07 02:03
See here https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/118#issuecomment-2041274963

**Comment by halirutan** [comment] 2024-04-10 00:54
Duplicate of #118

**Closed** 2024-04-10 00:54 UTC
Labels: feature-request
