### ISSUE TITLE
IntelliJ won't start with KeyPromotor X

### ISSUE THREAD

**Issue by timprijn** [halirutan/IntelliJ-Key-Promoter-X#5] opened 2017-08-12 08:45 UTC
Hi,

I've used KeyPromotor succesfully a couple of days and really liked it. Unfortunately it stopped working and I can't find the reason why or what I've changed in my configuration. During a restart IntelliJ stopped working. I use IntelliJ Ultimate version 2017.2.1 on my Mac and besides the stable version I already tried a couple of release candidates (rc6 and rc7) found in the other open issues.

Thanks in advance for any suggestions.

Tim

 Hereby the stacktrace received during startup of IntelliJ.

```
java.lang.AssertionError
    at com.intellij.util.xmlb.MapBinding.deserializeKeyOrValue(MapBinding.java:195)
    at com.intellij.util.xmlb.MapBinding.deserialize(MapBinding.java:160)
    at com.intellij.util.xmlb.MapBinding.deserializeList(MapBinding.java:124)
    at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:54)
    at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
    at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:66)
    at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:234)
    at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:188)
    at com.intellij.configurationStore.KotlinAwareBeanBinding.deserialize(xmlSerializer.kt:184)
    at com.intellij.configurationStore.XmlSerializer.deserialize(xmlSerializer.kt:79)
    at com.intellij.configurationStore.DefaultStateSerializerKt.deserializeState(DefaultStateSerializer.kt:40)
    at com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:42)
    at com.intellij.configurationStore.StateGetter.getState(StorageBaseEx.kt:44)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:316)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:291)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:38)
    at de.halirutan.keypromoterx.KeyPromoter.<init>(KeyPromoter.java:46)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:469)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:475)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:482)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:434)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:420)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by halirutan** [comment] 2017-08-12 13:04
I'm sorry for the inconvenience. This all is related to loading and storing the statistics file, where I must have some OS/version specific issue somewhere. I've had at least 3 of the same reports and I fail to reproduce them. Would it be possible that you put your statistics-file on [pastebin](https://pastebin.com/) (or some other site) for me, so that I can take a closer look at it? It only contains your shortcut-information and no personal data whatsoever.

You find this `xml` file in the following way:

1. Go in IDEA to Help -> Show Log in File Manager. This gives you the log-folder. For me, it is under `/home/patrick/.IdeaIC2017.1/system/log/`
2. Navigate to the following equivalent folder on your machine `/home/patrick/.IdeaIC2017.1/config/options/` and there should be a file that looks like `KeyPromoterXStatistic.xml`

The workaround is to delete this file when IDEA is not open and restart IDEA, but I'd rather have this be fixed once and for all. I know where it goes wrong, but I just don't see *why* my statistics-settings should fail to load after some time. Maybe there is a null-value anywhere. I really need to inspect this.

**Comment by timprijn** [comment] 2017-08-12 13:47
I've send you the file and tried out the workaround which works indeed. The location of the file at my system was under `~/Library/Preferences/IntelliJIdea2017.2/options`. Hope the file contents will help locate the problem.

**Comment by halirutan** [comment] 2017-08-13 01:15
I could reproduce the issue. All this trouble has its reason in [this line of code](https://github.com/halirutan/IntelliJ-Key-Promoter-X/blob/cb64384a9df572091df18b3e388bcc2b41255bdc/src/de/halirutan/keypromoterx/KeyPromoter.java#L128-L129). As this issue has bothered several users, I'm going to explain where if f*cked up.

I'm listening to all your mouse clicks and I try to find out, which action you have invoked when you clicked. Sometimes, you don't invoke a meaningful action at all, like when you just place the cursor with the mouse. If you indeed clicked and invoked some action like opening a tool-window, the next task is to find out

1. What action did you invoke (the so-called `ActionID`)?
2. Has this action a meaningful description?
3. Are there shortcuts for this action?

Unfortunately, there is no unique way to find this out for everything you press and I have to inspect several cases. In the end, I hopefully can collect all necessary data inside a `KeyPromoterAction` object which is later stored in the file on disk. The entries on disk always look like that

```xml
<Statistic Action="Project">
  <Item>
    <IdeaActionID>ActivateProjectToolWindow</IdeaActionID>
    <ShortCut>'⌘+1'</ShortCut>
    <Description>Project</Description>
    <Count>7</Count>
  </Item>
</Statistic>
```
As you can see, I have put the `Description` as an `Action` attribute to the `Statistic` tag. This felt like a good plan when I ever have to look at the statistic-file. Unfortunately, I have these lines in the code that *should* ensure only valid entries end up in the statistic

```java
if (!StringUtil.isEmpty(shortcut)) {
    statsService.registerAction(action);
   ...
```

Although I'm sure all of you already see where this is going, I point it out anyway: Guess what happens if you manage to click something that has a shortcut but no description. Right, we end up with an entry like this

```xml
<Statistic>
  <Item>
     <IdeaActionID />
     <ShortCut>'Button1 Double-Click'</ShortCut>
     <Description />
     <Count>1</Count>
  </Item>
</Statistic>
```

During the session, such entries won't be a problem, but when you close IDEA, these entries are written into the `xml` file. On the next startup, IDEA tries to load the `xml` file but assumes every `Statistic` tag has the `Action` attribute. You know what happens next. 

![1u073l](https://user-images.githubusercontent.com/511683/29245257-bf52329c-7fd4-11e7-92ee-aedabf63103d.jpg)

I'm pushing a fix in the next release.

**Comment by halirutan** [comment] 2017-08-13 02:55
Please try this build

https://github.com/halirutan/IntelliJ-Key-Promoter-X/releases/download/v5.8/Key-Promoter-X-5.8.zip

and remove the `KeyPromoterXStatistic.xml` before you open IDEA.

**Closed by halirutan** 2017-08-13 02:55 UTC
